mySite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leagues.urls')),
    path('posts/', include(('posts.urls'), namespace='posts')),
    path('', RedirectView.as_view(pattern_name='posts:posts_list', permanent=False)),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="posts_list"),
    path('<slug:slug>/', views.post_detail, name='post_detail'), 

]

posts/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    CATEGORY_CHOICES = [
        ('news', 'News'),
        ('predictions', 'Predictions'),
        ('results', 'Results'),
        ('analysis', 'Analysis'),
        ('general', 'General'),
        ('rewind', 'Rewind'),
        ('player_ratings', 'Player Ratings'),
        ('team_ratings', 'Team Ratings'),
        ('league_ratings', 'League Ratings'),
        ('drop_zone', 'Drop Zone'),
    ]

    title = models.CharField(max_length=95)
    body = models.TextField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/',blank=True, null=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='general')
    cloudinary_url = models.URLField(max_length=500,blank=True, null=True)


    def get_absolute_url(self):
        return reverse("post_detail", args=[self.slug]) 

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    

    

posts/views.py
from django.shortcuts import render, get_object_or_404
from.models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
            # If page is not an integer, deliver first page.
         page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results.
        page_obj = paginator.page(paginator.num_pages)
    return render(request, 'posts/post_lists.html', {'posts': posts})
    


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'posts/post_detail.html', {'post': post})

posts/templates/posts/post_lists.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}Blog | Punters-League{% endblock title %}

{% block content %}

 <div class="main-body">
<div class="web-logo">
<img rel="Icon" src="{% static 'images/web-logo.png' %}" alt="Website logo" width="200px" height="170px"><br>


</div>
<div class="social-icons">
    <a href="https://facebook.com/profile.php?id=61579007960417" target="_blank"><img src="{% static 'images/facebookicon.png' %}" alt="Facebook"></a>
    <a href="https://x.com/PuntersLeague1" target="_blank"><img src="{% static 'images/xicon.png' %}" alt="X"></a>
    <a href="https://www.youtube.com/channel/UClNp2eY92X1psjFR2cP-Rnw" target="_blank"><img src="{% static 'images/youtube-image.png' %}" alt="YouTube"></a>
    <p id="time"></p>
  </div><img rel="Icon" src="{% static 'images/haland.jpeg' %}" alt="Haland" width="200px" height="170px"><br>
  <p>Making use of the resource we have in this website will enable you start making 
    better betting decisions.
  </p>
  <p>These predictions are based on recent form and overall team strength. A value above 60
     indicates strong attacking or defensive performance, while lower values suggest vulnerability.
      The prediction column shows our expected outcome: 1 (Home Win), 2 (Away Win), or X (Draw).
       Keep checking daily for updated predictions based on new stats and performance trends</p>
  </div>
<div class="main-body">
    
  <h1>  All Topics </h1>
<ul>
    {% for post in posts %}
        <li>
            
            <a href="{% url 'posts:post_detail' slug=post.slug %}">
    {{post.title}}
</a>



        <small>({{ post.date|date:"M d, Y" }})</small>
        </li>
    {% empty %}
        <li>No posts available.</li>
    {% endfor %}
</ul>

</div>
<!--
{% for post in posts %}
    <h2><a href="{% url 'posts:post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
    <p>{{ post.date }}</p>
    <p>{{ post.content|truncatewords:30 }}</p>
{% empty %}
    <p>No posts available.</p>
{% endfor %}
-->
{% endblock %}